import {useEffect,useMemo,useState} from 'react';
import {Play,Pause,Check,RotateCcw,Timer,ChevronRight,CalendarPlus,HeartPulse} from 'lucide-react';
import {useHealthStore} from '../domain/healthStore';
import {today,addDays,dateLabel} from './dates';
import {IntegrationPanel,type IntegrationOccurrence} from '../integrations/IntegrationPanel';
type Category='Walk & cardio'|'Strength'|'Mobility'|'Balance'|'Seated'|'Yoga';
type Exercise={id:string;name:string;category:Category;minutes:number;reps:number;sets:number;equipment:string;impact:'Low'|'Moderate';muscle:string;steps:string[];cue:string;modification:string;avoid:string;};
const seeds:[string,Category,string,string,string][]=[
 ['Brisk walk','Walk & cardio','None','Whole body','Walk tall, land softly, keep a pace that allows brief phrases.'],['March in place','Walk & cardio','None','Whole body','Lift knees comfortably and swing arms in a steady rhythm.'],['Step-up','Walk & cardio','Step','Legs','Place the full foot on a stable step, stand tall, then step down slowly.'],['Sit-to-stand','Strength','Chair','Legs','Scoot forward, press through your feet, stand without pulling on your knees.'],['Wall push-up','Strength','Wall','Chest','Hands at chest height, body in one line, bend elbows then press away.'],['Glute bridge','Strength','Mat','Hips','Lie on your back, squeeze glutes to lift hips, lower with control.'],['Bird dog','Strength','Mat','Core','From hands and knees, extend opposite arm and leg without twisting.'],['Band row','Strength','Resistance band','Back','Anchor safely, pull elbows toward ribs, pause, return slowly.'],['Calf raise','Strength','Chair','Calves','Hold support lightly, rise through forefeet, lower fully.'],['Dead bug','Strength','Mat','Core','Keep ribs quiet, lower opposite arm and leg only as far as your back stays neutral.'],['Cat-cow','Mobility','Mat','Spine','Move slowly between a rounded back and gentle chest opening.'],['Hip hinge drill','Mobility','Chair','Hips','Reach hips back toward the chair while keeping a long spine.'],['Ankle circles','Mobility','Chair','Ankles','Make slow controlled circles in each direction.'],['Chest opener','Mobility','None','Shoulders','Clasp hands behind you only if comfortable; gently broaden across the chest.'],['Single-leg balance','Balance','Chair','Balance','Stand close to a chair, shift weight to one leg, keep a soft knee.'],['Heel-to-toe walk','Balance','Wall','Balance','Walk slowly with heel touching toe, using a wall for support.'],['Seated march','Seated','Chair','Hips','Sit tall and alternate lifting one knee at a time.'],['Seated press','Seated','Water bottles','Shoulders','Press light objects overhead only through a comfortable range.'],['Box breathing','Yoga','None','Breath','Inhale four, pause four, exhale four, pause four without strain.'],['Chair sun salutation','Yoga','Chair','Whole body','Use the chair to support a slow reach, fold, and stand sequence.']];
const variations=['Foundation','Gentle','Steady','Supported'];
const exercises:Exercise[]=seeds.flatMap((s,base)=>variations.slice(0,base<10?4:3).map((v,n)=>({id:`${s[0].toLowerCase().replace(/[^a-z]+/g,'-')}-${n}`,name:`${v} ${s[0]}`,category:s[1],equipment:s[2],muscle:s[3],minutes:s[1]==='Walk & cardio'?10+n*5:6+n*2,reps:s[1]==='Walk & cardio'||s[1]==='Yoga'?0:8+n*2,sets:s[1]==='Walk & cardio'||s[1]==='Yoga'?1:2+n%2,impact:n<2?'Low':'Moderate',steps:[s[4],'Breathe steadily; stop if you feel sharp pain, dizziness, chest pressure, or unusual breathlessness.','Rest and record how it felt before moving on.'],cue:'Move with control. A comfortable effort matters more than speed.',modification:'Use less range, fewer repetitions, extra support, or choose the seated option.',avoid:'Do not use this routine as a substitute for individualized clinical or rehabilitation advice.'})));
const routines=[['Gentle reset',['cat-cow-0','sit-to-stand-1','seated-march-0']],['Beginner strength',['sit-to-stand-0','wall-push-up-0','glute-bridge-0']],['Desk mobility',['chest-opener-0','ankle-circles-0','cat-cow-0']],['Walk steady',['brisk-walk-0','calf-raise-0','single-leg-balance-0']],['Chair confidence',['seated-march-0','seated-press-0','heel-to-toe-walk-0']],['Core basics',['bird-dog-0','dead-bug-0','glute-bridge-0']],['Balance basics',['single-leg-balance-0','heel-to-toe-walk-0','calf-raise-0']],['Band back',['band-row-0','wall-push-up-0','hip-hinge-drill-0']],['Low-impact cardio',['march-in-place-1','step-up-1','box-breathing-0']],['Yoga pause',['chair-sun-salutation-0','cat-cow-0','box-breathing-0']],['Full-body support',['sit-to-stand-3','wall-push-up-3','band-row-3']],['Weekend walk',['brisk-walk-2','hip-hinge-drill-0','chest-opener-0']]] as const;
function demo(exercise:Exercise){return <div aria-label={`Original illustrated movement guide for ${exercise.name}`}><img className="exercise-snapshot" src={`${import.meta.env.BASE_URL}graphics/exercise-flow.svg`} alt={`Three-step movement infographic for ${exercise.name}: set up, move with control, then recover.`}/><div className="exercise-demo"><span>1</span><i>↗</i><span>2</span><i>↘</i><small>Original movement guide · read the steps below</small></div></div>}
export function Exercise(){const {state,update}=useHealthStore();const [query,setQuery]=useState('');const [category,setCategory]=useState<Category|'All'>('All');const [chosen,setChosen]=useState<Exercise|null>(null);const [active,setActive]=useState<any|null>(null);const [running,setRunning]=useState(false);const [seconds,setSeconds]=useState(0);const [completed,setCompleted]=useState<Record<string,number>>({});const [effort,setEffort]=useState(4);const [message,setMessage]=useState('');
 useEffect(()=>{if(!running)return;const started=Date.now()-seconds*1000;const timer=setInterval(()=>setSeconds(Math.max(0,Math.round((Date.now()-started)/1000))),500);return()=>clearInterval(timer);},[running]);
 useEffect(()=>{const saved=state.activeWorkout;if(saved){setActive(saved);setCompleted(saved.completed||{});setSeconds(saved.seconds||0);setEffort(saved.effort||4);}},[state.activeWorkout?.id]);
 const rows=useMemo(()=>exercises.filter(e=>(category==='All'||e.category===category)&&`${e.name} ${e.equipment} ${e.muscle}`.toLowerCase().includes(query.toLowerCase())),[query,category]);
 const suitable=state.profile.limitations||state.profile.conditions?.some((c:string)=>/pregnan|advanced|recent surgery/i.test(c));const scheduled=(state.occurrences||[]) as IntegrationOccurrence[];
 async function persist(next:any){await update(s=>{s.activeWorkout=next;});}
 async function start(list:Exercise[],title:string){if(suitable){setMessage('Your health context is marked for individual guidance. Review the movements and use clinician-approved options before starting.');return;}const next={id:crypto.randomUUID(),title,startedAt:new Date().toISOString(),steps:list,completed:{},seconds:0,effort:4,status:'active'};setActive(next);setCompleted({});setSeconds(0);setRunning(true);await persist(next);}
 async function finish(){if(!active)return;const session={...active,status:'completed',endedAt:new Date().toISOString(),completed,seconds,effort};const ok=await update(s=>{s.sessions.push(session);s.activeWorkout=null;});if(ok){setActive(null);setRunning(false);setMessage('Workout saved. Your next progression stays a suggestion for you to accept.');}}
 const workout=active?.steps?.map((s:any)=>exercises.find(e=>e.id===s.id)||s)||[];
 return <div className="page-stack"><header className="page-heading"><div><span className="eyebrow">MOVE AT YOUR OWN PACE</span><h1>Strength is a practice.<br/><em>Start where you are.</em></h1><p>Choose a routine, follow the cues, and record what you actually did.</p></div><button className="secondary" onClick={()=>setChosen(exercises.find(e=>e.category==='Seated')||null)}>Need a gentle start</button></header>{message&&<p className="notice" role="status">{message}</p>}
 {active?<section className="surface player"><header><div><span className="eyebrow">ACTIVE SESSION</span><h2>{active.title}</h2><p className="timer"><Timer size={20}/>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</p></div><button className="primary" onClick={()=>setRunning(!running)}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Pause':'Resume'}</button></header>{workout.map((e:Exercise,index:number)=><article className="workout-step" key={e.id}>{demo(e)}<div><span className="eyebrow">MOVEMENT {index+1} · {e.category}</span><h3>{e.name}</h3><p>{e.sets>1?`${e.sets} sets × ${e.reps} reps`:`${e.minutes} minutes`} · {e.equipment}</p><ol>{e.steps.map(x=><li key={x}>{x}</li>)}</ol><p className="muted">Modify: {e.modification}</p><div className="button-row"><label>Completed sets <input type="number" min="0" max={e.sets||1} value={completed[e.id]||0} onChange={ev=>{const n=Math.max(0,Math.min(e.sets||1,Number(ev.target.value)));setCompleted(c=>({...c,[e.id]:n}));void persist({...active,completed:{...completed,[e.id]:n},seconds,effort});}}/></label><button className="secondary" onClick={()=>setChosen(e)}>Substitute</button></div></div></article>)}<div className="form-grid"><label>Effort, 1 easy to 10 hard<input type="range" min="1" max="10" value={effort} onChange={e=>setEffort(Number(e.target.value))}/></label><button className="primary" onClick={()=>void finish()}><Check size={17}/> Finish and save</button></div></section>:<><section className="surface routine-strip"><div className="section-heading"><div><span className="eyebrow">STARTER ROUTINES</span><h2>Choose a small win</h2></div></div>{routines.map(([name,ids])=><button key={name} onClick={()=>void start(ids.map(id=>exercises.find(e=>e.id===id)).filter(Boolean) as Exercise[],name)}><strong>{name}</strong><small>{ids.length} movements</small><ChevronRight size={16}/></button>)}</section><section className="surface"><div className="section-heading"><div><span className="eyebrow">EXERCISE LIBRARY</span><h2>Find a movement</h2></div><input aria-label="Search exercises" placeholder="Search movement or equipment" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="segmented categories"><button aria-pressed={category==='All'} onClick={()=>setCategory('All')}>All</button>{(['Walk & cardio','Strength','Mobility','Balance','Seated','Yoga'] as Category[]).map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="exercise-grid">{rows.map(e=><button className="exercise-card" key={e.id} onClick={()=>setChosen(e)}>{demo(e)}<span className="eyebrow">{e.category} · {e.impact} impact</span><h3>{e.name}</h3><p>{e.sets>1?`${e.sets} × ${e.reps} reps`:`${e.minutes} minutes`} · {e.equipment}</p></button>)}</div></section></>}
 {chosen&&<aside className="drawer" role="dialog" aria-modal="true" aria-label={chosen.name}><button className="close" onClick={()=>setChosen(null)}>Close</button>{demo(chosen)}<span className="eyebrow">{chosen.category} · {chosen.impact} impact</span><h2>{chosen.name}</h2><p>{chosen.sets>1?`${chosen.sets} sets × ${chosen.reps} reps`:`${chosen.minutes} minutes`} · {chosen.equipment}</p><ol>{chosen.steps.map(x=><li key={x}>{x}</li>)}</ol><p><strong>Technique cue:</strong> {chosen.cue}</p><p><strong>Modification:</strong> {chosen.modification}</p><p className="muted">{chosen.avoid}</p><button className="primary" onClick={()=>void start([chosen],chosen.name)}><Play size={17}/> Start movement</button></aside>}
 <section className="workspace-split"><section className="surface"><span className="eyebrow">YOUR WEEK</span><h2>Schedule a session</h2><p className="muted">Calendar receives timed reminders. Tasks receives dated completion checklists.</p><Schedule onAdd={async entry=>{await update(s=>{s.occurrences.push(entry);});setMessage('Workout scheduled locally. Connect Google to export it.');}}/></section><IntegrationPanel occurrences={scheduled} onCompletionChange={(id,done)=>void update(s=>{const row=s.occurrences.find((x:any)=>x.id===id);if(row)row.completed=done;})}/></section></div>}
function Schedule({onAdd}:{onAdd:(entry:IntegrationOccurrence)=>Promise<void>}){const [date,setDate]=useState(today());const [time,setTime]=useState('07:00');const [title,setTitle]=useState('Health Planner workout');return <form className="form-grid" onSubmit={e=>{e.preventDefault();void onAdd({id:crypto.randomUUID(),title,date,startTime:time,durationMinutes:30,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,completed:false,revision:1});}}><label>Workout title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Date<input type="date" min={today()} value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><button className="primary"><CalendarPlus size={17}/> Add reminder</button></form>}
