import {useMemo,useState} from 'react';
import {BarChart,Bar,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {useHealthStore} from '../domain/healthStore';

type Period='7'|'30';
const kcal=(entry:any)=>{const value=entry.calories??entry.recipe?.nutrients?.calories;return typeof value==='number'?Math.round(value*(entry.portions||1)):null;};
export function Insights(){
 const {state}=useHealthStore();const [period,setPeriod]=useState<Period>('7');
 const days=useMemo(()=>[...state.diary].sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(-Number(period)),[state.diary,period]);
 const meals=days.flatMap(day=>day.foodLogs||day.recipe?[...(day.foodLogs||[]),...(day.recipe?[day]:[])]:[]);
 const chart=days.map(day=>{const records=day.foodLogs||day.recipe?[...(day.foodLogs||[]),...(day.recipe?[day]:[])]:[];const values=records.map(kcal).filter((x):x is number=>x!==null);return {date:String(day.date).slice(5),calories:values.length?values.reduce((sum,x)=>sum+x,0):null,weight:typeof day.weightKg==='number'?day.weightKg:null,meals:records.length};});
 const sessions=state.sessions.filter((s:any)=>s.status==='completed');const frequency=new Map<string,number>();meals.forEach((f:any)=>frequency.set(f.name||f.recipe?.name,(frequency.get(f.name||f.recipe?.name)||0)+1));const favorites=[...frequency.entries()].filter(([name])=>name).sort((a,b)=>b[1]-a[1]).slice(0,8);
 const flags=(state.profile.conditions||[]).join(' ').toLowerCase();const focus=[/masld|nafld|fatty liver/.test(flags)&&'MASLD / fatty-liver focus: prioritize consistent meals, fibre-rich choices, and clinician-reviewed liver follow-up.',/diabet|prediabet/.test(flags)&&'Diabetes focus: review carbohydrate estimates and meal timing with your clinician; values here are planning estimates.',/sedentary|desk|it|inactive/.test(`${flags} ${state.profile.goal||''}`)&&'Desk-day focus: schedule short movement breaks and build from a sustainable baseline.'].filter(Boolean) as string[];
 return <div className="page-stack"><header className="page-heading"><div><div className="eyebrow">INTERACTIVE DASHBOARD</div><h1>See the pattern.<br/><em>Choose the next step.</em></h1><p className="muted">Charts only use records you enter. Planned meals and missing days never become consumption data.</p></div><div className="segmented" aria-label="Dashboard range">{(['7','30'] as Period[]).map(value=><button key={value} aria-pressed={period===value} onClick={()=>setPeriod(value)}>{value} days</button>)}</div></header>
 <section className="stats-row"><div className="panel"><strong>{days.length}</strong><span>Recorded days in view</span></div><div className="panel"><strong>{meals.length}</strong><span>Meals logged in view</span></div><div className="panel"><strong>{sessions.length}</strong><span>Completed workouts</span></div></section>
 {focus.length>0&&<section className="surface focus-panel"><span className="eyebrow">YOUR PLANNING PRIORITIES</span><h2>Support the context you shared</h2><ul>{focus.map(note=><li key={note}>{note}</li>)}</ul><p className="muted">This is general planning support, not a diagnosis or treatment plan.</p></section>}
 <section className="dashboard-grid"><section className="panel chart-panel"><div className="section-heading"><div><span className="eyebrow">FOOD DIARY</span><h2>Logged energy</h2></div><span className="pill">kcal</span></div>{chart.some(x=>x.calories!==null)?<ResponsiveContainer width="100%" height={240}><BarChart data={chart}><CartesianGrid stroke="currentColor" opacity={.12} vertical={false}/><XAxis dataKey="date" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="calories" fill="currentColor" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer>:<p className="empty-state">Log a meal to start this chart.</p>}</section>
 <section className="panel chart-panel"><div className="section-heading"><div><span className="eyebrow">WEIGHT TREND</span><h2>Recorded measurements</h2></div><span className="pill">kg</span></div>{chart.filter(x=>x.weight!==null).length>1?<ResponsiveContainer width="100%" height={240}><LineChart data={chart}><CartesianGrid stroke="currentColor" opacity={.12} vertical={false}/><XAxis dataKey="date" tickLine={false} axisLine={false}/><YAxis domain={['dataMin - 1','dataMax + 1']} tickLine={false} axisLine={false}/><Tooltip/><Line type="monotone" dataKey="weight" stroke="currentColor" strokeWidth={3} dot={{r:3}} connectNulls/></LineChart></ResponsiveContainer>:<p className="empty-state">Add at least two dated weight records to view a trend.</p>}</section></section>
 <section className="panel"><h2>Meals you return to</h2>{favorites.length?<ol className="simple-list">{favorites.map(([name,count])=><li key={name}><span>{name}</span><span>{count} logged</span></li>)}</ol>:<p className="empty-state">Log meals in your diary to discover your favorites.</p>}</section>
 </div>;
}
