import React, {useState} from 'react';
import {useHealthStore} from '../domain/healthStore';
const steps=['Your starting point','Food & preferences','Everyday cooking','Health context','Movement','Your schedule','Review & begin'];
export function Onboarding({onClose}:{onClose?:()=>void}){
 const {state,update}=useHealthStore();const p=state.profile;const step=state.onboarding.step;const [error,setError]=useState('');
 const save=(key:string,value:any)=>void update(d=>{d.profile[key]=value;});
 const field=(key:string,label:string,type='text',hint='')=><label className="field" key={key}><span>{label}</span><input type={type} value={p[key]??''} min={type==='number'?0:undefined} onChange={e=>save(key,type==='number'?(e.target.value===''?undefined:Number(e.target.value)):e.target.value)}/>{hint&&<small>{hint}</small>}</label>;
 const list=(key:string,label:string)=>field(key,label+' (comma separated)');
 const csv=(key:string,label:string)=><label className="field" key={key}><span>{label}</span><input defaultValue={(p[key]||[]).join(', ')} placeholder="Separate with commas; leave blank if unknown" onBlur={e=>save(key,e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label>;
 const select=(key:string,label:string,values:string[])=><label className="field" key={key}><span>{label}</span><select value={p[key]||''} onChange={e=>save(key,e.target.value)}><option value="">Choose or leave unknown</option>{values.map(x=><option key={x}>{x}</option>)}</select></label>;
 async function next(){setError('');if(step===0&&(!p.name.trim()||(p.age!==undefined&&(p.age<18||p.age>120)))){setError('Enter your name and, if supplied, an adult age between 18 and 120.');return;}if(step<6)await update(d=>{d.onboarding.step++;});else {const ok=await update(d=>{d.onboarding.complete=true;d.profile.onboarded=true;});if(ok)onClose?.();}}
 return <section className="panel onboarding"><div className="eyebrow">PERSONAL SETUP · {step+1} OF 7</div><h1>{steps[step]}</h1><p className="muted">Your answers save on this device. Optional fields can stay unknown and be updated later.</p><progress aria-label="Setup progress" value={step+1} max={7}/><div className="form-grid" key={step}>
 {step===0&&<>{field('name','What should we call you?')}{field('age','Age (optional)','number')}{field('heightCm','Height · cm','number')}{field('weightKg','Current weight · kg','number')}{field('targetWeightKg','Target weight · kg (optional)','number')}{select('goal','Your focus',['Build consistent habits','Maintain weight','Manage weight with guidance','Improve strength and fitness','Support a clinician-led health plan'])}</>}
 {step===1&&<>{select('dietaryPreference','Dietary preference',['pure_veg','vegan','eggetarian','non_veg'])}{csv('allergies','Allergies — ingredients to exclude')}{csv('dislikes','Foods you dislike')}{csv('cuisines','Preferred cuisines')}{field('religiousRestrictions','Religious or cultural food restrictions')}</>}
 {step===2&&<>{field('budget','Weekly food budget and currency')}{field('cookingMinutes','Available cooking time · minutes','number')}{field('householdSize','People you cook for','number')}{field('cookingEquipment','Cooking equipment')}{select('mealPrep','Meal preparation',['Cook daily','Batch cook','Mix of home and purchased meals'])}</>}
 {step===3&&<>{csv('conditions','Clinician-diagnosed conditions')}{field('medications','Medicines and supplements (optional)')}{select('pregnancy','Pregnancy / breastfeeding',['unknown','Not applicable','Pregnant','Breastfeeding'])}{field('clinicalNotes','Clinician instructions and relevant history')}{field('kidneyHistory','Kidney disease or clinician-set protein/fluid limits')}{field('eatingHistory','Eating disorder or fasting-related concerns (optional)')}<p className="muted">Add dated laboratory results in Health after setup. The app does not diagnose conditions or prescribe medication or fasting.</p></>}
 {step===4&&<>{select('exerciseExperience','Exercise experience',['New to exercise','Returning after a break','Regularly active'])}{field('limitations','Pain, injuries, mobility limits or clinician restrictions')}{csv('equipment','Available equipment')}{field('exerciseMinutes','Time available per session · minutes','number')}{field('exerciseDays','Preferred exercise days')}</>}
 {step===5&&<>{field('timezone','Time zone (IANA name)')}{field('wakeTime','Typical wake time','time')}{field('mealTimes','Meal times, e.g. 08:00,13:00,19:00')}{field('reminderTime','Preferred exercise time','time')}<p className="muted">Google reminders are optional. Connect your account and review the event preview in Settings.</p></>}
 {step===6&&<><dl className="review-list">{Object.entries(p).filter(([k,v])=>!['onboarded'].includes(k)&&v!==''&&v!==undefined&&(!Array.isArray(v)||v.length)).map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd>{Array.isArray(v)?v.join(', '):String(v)}</dd></div>)}</dl><p className="muted">No missing health measurement has been filled with a sample value. Add laboratory observations in Health whenever you have a report.</p></>}
 </div>{error&&<p role="alert">{error}</p>}<div className="toolbar">{step>0&&<button onClick={()=>void update(d=>{d.onboarding.step--;})}>Back</button>}<button className="primary" onClick={()=>void next()}>{step===6?'Start my planner':'Continue'}</button>{onClose&&<button onClick={onClose}>Save & close</button>}</div></section>;
}
