import React,{useMemo,useState} from 'react';
import {useHealthStore} from '../domain/healthStore';
import {authorizeGoogle} from '../services/gdrive/auth.service';
import {gDriveService} from '../services/gdrive/gdrive.service';
import {GOOGLE_SCOPES} from '../config/gdrive.config';

const steps=['Connect & restore','Your starting point','Food & preferences','Everyday cooking','Health context','Movement','Your schedule','Review & begin'];
const encouragement=['Your data stays yours. Start from where you are.','A few details make every suggestion more useful.','Food preferences are a strength, not a restriction.','A practical plan fits the way you actually live.','Context helps you plan; it does not label or diagnose you.','Small movement breaks count, especially on desk-heavy days.','A reminder can turn intention into an easier next step.','You built a plan that can adapt with you.'];
function Sparkline(){return <svg className="onboarding-sparkline" viewBox="0 0 260 72" aria-label="Illustrative progress trend"><path d="M4 62C42 59 43 48 74 50s37-28 69-22 42-18 67-16 29-9 46-12" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><circle cx="256" cy="12" r="5" fill="currentColor"/></svg>}
export function Onboarding({onClose}:{onClose?:()=>void}){
 const {state,update,importData}=useHealthStore();const p=state.profile;const step=state.onboarding.step||0;const [error,setError]=useState('');const [restoring,setRestoring]=useState(false);const [restoreStatus,setRestoreStatus]=useState('');
 const completion=useMemo(()=>Math.round((step/7)*100),[step]);
 const save=(key:string,value:any)=>void update(d=>{d.profile[key]=value;});
 const field=(key:string,label:string,type='text',hint='')=><label className="field" key={key}><span>{label}</span><input type={type} value={p[key]??''} min={type==='number'?0:undefined} onChange={e=>save(key,type==='number'?(e.target.value===''?undefined:Number(e.target.value)):e.target.value)}/>{hint&&<small>{hint}</small>}</label>;
 const csv=(key:string,label:string)=><label className="field" key={key}><span>{label}</span><input defaultValue={(p[key]||[]).join(', ')} placeholder="Separate with commas; leave blank if unknown" onBlur={e=>save(key,e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label>;
 const select=(key:string,label:string,values:string[])=><label className="field" key={key}><span>{label}</span><select value={p[key]||''} onChange={e=>save(key,e.target.value)}><option value="">Choose or leave unknown</option>{values.map(x=><option key={x}>{x}</option>)}</select></label>;
 async function restore(){setError('');setRestoreStatus('Opening Google sign-in…');setRestoring(true);try{await authorizeGoogle(['openid',GOOGLE_SCOPES.DRIVE_APPDATA]);const file=await gDriveService.findStoreFile();if(!file){setRestoreStatus('No Health Planner backup was found in this Google account. You can continue with this device.');return;}const data=await gDriveService.downloadStore(file.id);if(await importData(JSON.stringify(data))){setRestoreStatus('Saved items restored to this device. Continue to review your plan.');}else setRestoreStatus('A backup was found but could not be safely restored. Your local data was left unchanged.');}catch(e){setError(e instanceof Error?e.message:'Google restore could not finish. You can continue without restoring.');setRestoreStatus('');}finally{setRestoring(false);}}
 async function next(){setError('');if(step===1&&(!p.name.trim()||(p.age!==undefined&&(p.age<18||p.age>120)))){setError('Enter your name and, if supplied, an adult age between 18 and 120.');return;}if(step<7)await update(d=>{d.onboarding.step++;});else {const ok=await update(d=>{d.onboarding.complete=true;d.profile.onboarded=true;});if(ok)onClose?.();}}
 return <section className="panel onboarding"><div className="onboarding-topline"><div><div className="eyebrow">PERSONAL SETUP · {step+1} OF 8</div><h1>{steps[step]}</h1></div><div className="onboarding-score"><strong>{completion}%</strong><span>set up</span></div></div><p className="muted">{encouragement[step]}</p><div className="onboarding-progress"><progress aria-label="Setup progress" value={step+1} max={8}/><Sparkline/></div>
 {step===0?<section className="restore-card"><div><span className="eyebrow">OPTIONAL · PRIVATE DRIVE BACKUP</span><h2>Bring back your saved items</h2><p>Connect your Google account to look only in Health Planner’s private app-data folder. Your access token stays in memory and no health record is placed in a public repository.</p></div><button className="primary" disabled={restoring} onClick={()=>void restore()}>{restoring?'Checking Google Drive…':'Connect Google & restore saved items'}</button>{restoreStatus&&<p className="notice" role="status">{restoreStatus}</p>}<p className="muted">No backup? Continue with this device. You can connect Calendar, Tasks, or Drive again later.</p></section>:<div className="form-grid" key={step}>
 {step===1&&<>{field('name','What should we call you?')}{field('age','Age (optional)','number')}{field('heightCm','Height · cm','number')}{field('weightKg','Current weight · kg','number')}{field('targetWeightKg','Target weight · kg (optional)','number')}{select('goal','Your focus',['Build consistent habits','Maintain weight','Manage weight with guidance','Improve strength and fitness','Support a clinician-led health plan'])}<section className="metric-preview"><strong>{p.targetWeightKg&&p.weightKg?`${Math.abs(p.weightKg-p.targetWeightKg).toFixed(1)} kg`:'Your pace'}</strong><span>is built through repeatable choices, not perfect days.</span></section></>}
 {step===2&&<>{select('dietaryPreference','Dietary preference',['pure_veg','vegan','eggetarian','non_veg'])}{csv('allergies','Allergies — ingredients to exclude')}{csv('dislikes','Foods you dislike')}{csv('cuisines','Preferred cuisines')}{field('religiousRestrictions','Religious or cultural food restrictions')}</>}
 {step===3&&<>{field('budget','Weekly food budget and currency')}{field('cookingMinutes','Available cooking time · minutes','number')}{field('householdSize','People you cook for','number')}{field('cookingEquipment','Cooking equipment')}{select('mealPrep','Meal preparation',['Cook daily','Batch cook','Mix of home and purchased meals'])}</>}
 {step===4&&<>{csv('conditions','Clinician-diagnosed conditions')}{field('medications','Medicines and supplements (optional)')}{select('pregnancy','Pregnancy / breastfeeding',['unknown','Not applicable','Pregnant','Breastfeeding'])}{field('clinicalNotes','Clinician instructions and relevant history')}{field('kidneyHistory','Kidney disease or clinician-set protein/fluid limits')}{field('eatingHistory','Eating disorder or fasting-related concerns (optional)')}<p className="muted">Add dated laboratory results in Health after setup. The app does not diagnose conditions or prescribe medication or fasting.</p></>}
 {step===5&&<><label className="field"><span>Typical desk-day movement · minutes</span><input type="range" min="0" max="120" step="5" value={p.activityMinutes??30} onChange={e=>save('activityMinutes',Number(e.target.value))}/><strong>{p.activityMinutes??30} minutes</strong></label>{select('exerciseExperience','Exercise experience',['New to exercise','Returning after a break','Regularly active'])}{field('limitations','Pain, injuries, mobility limits or clinician restrictions')}{csv('equipment','Available equipment')}{field('exerciseMinutes','Time available per session · minutes','number')}<section className="metric-preview"><strong>{Math.max(1,Math.round((p.activityMinutes??30)/5))} movement breaks</strong><span>could fit into a desk-heavy day. Choose what feels realistic.</span></section></>}
 {step===6&&<>{field('timezone','Time zone (IANA name)')}{field('wakeTime','Typical wake time','time')}{field('mealTimes','Meal times, e.g. 08:00,13:00,19:00')}{field('reminderTime','Preferred exercise time','time')}<p className="muted">Google reminders are optional. Connect your account and review the event preview in Settings.</p></>}
 {step===7&&<><dl className="review-list">{Object.entries(p).filter(([k,v])=>!['onboarded'].includes(k)&&v!==''&&v!==undefined&&(!Array.isArray(v)||v.length)).map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd>{Array.isArray(v)?v.join(', '):String(v)}</dd></div>)}</dl><section className="metric-preview"><strong>Ready to begin</strong><span>Your plan stays editable. Measurements remain separate from diagnoses, and no sample health data was added.</span></section></>}
 </div>}
 {error&&<p className="notice error" role="alert">{error}</p>}<div className="toolbar">{step>0&&<button onClick={()=>void update(d=>{d.onboarding.step--;})}>Back</button>}<button className="primary" onClick={()=>void next()}>{step===0?'Continue with this device':step===7?'Start my planner':'Continue'}</button>{onClose&&<button onClick={onClose}>Save & close</button>}</div></section>;
}
